In [2]:
import numpy as np

def rotation_matrix_to_xyz_fixed_angles(rotation_matrix):
    # Extract angles using trigonometric functions
    theta_x = np.arctan2(rotation_matrix[2, 1], rotation_matrix[2, 2])
    theta_y = np.arctan2(-rotation_matrix[2, 0], np.sqrt(rotation_matrix[2, 1]**2 + rotation_matrix[2, 2]**2))
    theta_z = np.arctan2(rotation_matrix[1, 0], rotation_matrix[0, 0])
    array = np.array([theta_x, theta_y, theta_z])
    return np.round(array, decimals=3)

def xyz_fixed_angles_to_rotation_matrix(angles):
    theta_x, theta_y, theta_z = angles
    
    # Compute rotation matrices for each axis
    Rx = np.array([[1, 0, 0],
                   [0, np.cos(theta_x), -np.sin(theta_x)],
                   [0, np.sin(theta_x), np.cos(theta_x)]])
    
    Ry = np.array([[np.cos(theta_y), 0, np.sin(theta_y)],
                   [0, 1, 0],
                   [-np.sin(theta_y), 0, np.cos(theta_y)]])
    
    Rz = np.array([[np.cos(theta_z), -np.sin(theta_z), 0],
                   [np.sin(theta_z), np.cos(theta_z), 0],
                   [0, 0, 1]])
    
    # Combine rotation matrices
    rotation_matrix = Rz @ Ry @ Rx
    
    return np.round(rotation_matrix, decimals=3)

In [3]:
def test_rotation_to_xyz_fixed_angles():
    rotation_matrix = np.array([[0.6124, -0.3536, 0.7071],
 [0.6124, 0.6124, -0.5],
 [ -0.5, 0.7071, 0.5]])

    print("Rotation Matrix:")
    print(rotation_matrix)
    print("")

    # Convert rotation matrix to XYZ fixed angles
    xyz_angles = rotation_matrix_to_xyz_fixed_angles(rotation_matrix)
    print("XYZ Fixed Angles:")
    print(xyz_angles)
    print("")

    # Convert XYZ fixed angles back to rotation matrix
    reversed_rotation_matrix = xyz_fixed_angles_to_rotation_matrix(xyz_angles)
    print("Reversed Rotation Matrix (XYZ Fixed Angles):")
    print(reversed_rotation_matrix)
    print("")

    
test_rotation_to_xyz_fixed_angles()

Rotation Matrix:
[[ 0.6124 -0.3536  0.7071]
 [ 0.6124  0.6124 -0.5   ]
 [-0.5     0.7071  0.5   ]]

XYZ Fixed Angles:
[0.955 0.524 0.785]

Reversed Rotation Matrix (XYZ Fixed Angles):
[[ 0.612 -0.119  0.781]
 [ 0.612  0.697 -0.373]
 [-0.5    0.707  0.5  ]]



In [28]:
def rotation_matrix_to_eulers_parameter(rotation_matrix):
    # Calculate Euler's parameters
    e0 = np.sqrt((rotation_matrix.trace() + 1) / 4)
    e1 = (rotation_matrix[1, 2] - rotation_matrix[2, 1]) / (4 * e0)
    e2 = (rotation_matrix[2, 0] - rotation_matrix[0, 2]) / (4 * e0)
    e3 = (rotation_matrix[0, 1] - rotation_matrix[1, 0]) / (4 * e0)
    array = np.array([e0, e1, e2, e3])
    return np.round(array, decimals=3)

def eulers_parameter_to_rotation_matrix(params):
    e0, e1, e2, e3 = params
    
    # Compute rotation matrix elements
    r11 = e0**2 + e1**2 - e2**2 - e3**2
    r12 = 2 * (e1 * e2 - e0 * e3)
    r13 = 2 * (e1 * e3 + e0 * e2)
    
    r21 = 2 * (e1 * e2 + e0 * e3)
    r22 = e0**2 - e1**2 + e2**2 - e3**2
    r23 = 2 * (e2 * e3 - e0 * e1)
    
    r31 = 2 * (e1 * e3 - e0 * e2)
    r32 = 2 * (e2 * e3 + e0 * e1)
    r33 = e0**2 - e1**2 - e2**2 + e3**2
    
    # Construct rotation matrix
    rotation_matrix = np.array([[r11, r12, r13],
                                [r21, r22, r23],
                                [r31, r32, r33]])
    
    return np.round(rotation_matrix, decimals=3)

In [29]:
def test_rotation_to_eulers_angles():
    rotation_matrix = np.array([[0.707, -0.707, 0],
                                [0.707, 0.707, 0],
                                [0, 0, 1]])

    print("Rotation Matrix:")
    print(rotation_matrix)
    print("")

    # Convert rotation matrix to Euler's angles
    eulers_angles = rotation_matrix_to_eulers_parameter(rotation_matrix)
    print("Euler's Angles:")
    print(eulers_angles)
    print("")

    # Convert Euler's angles back to rotation matrix
    reversed_rotation_matrix = eulers_parameter_to_rotation_matrix(eulers_angles)
    print("Reversed Rotation Matrix (Euler's Angles):")
    print(reversed_rotation_matrix)
    print("")

   

test_rotation_to_eulers_angles()

Rotation Matrix:
[[ 0.707 -0.707  0.   ]
 [ 0.707  0.707  0.   ]
 [ 0.     0.     1.   ]]

Euler's Angles:
[ 0.924  0.     0.    -0.383]

Reversed Rotation Matrix (Euler's Angles):
[[ 0.707  0.708  0.   ]
 [-0.708  0.707 -0.   ]
 [-0.     0.     1.   ]]



In [32]:
def rotation_matrix_to_zyz_fixed_angles(rotation_matrix):
    # Extract angles using trigonometric functions
    theta_z1 = np.arctan2(rotation_matrix[1, 2], rotation_matrix[0, 2])
    theta_y = np.arccos(rotation_matrix[2, 2])
    theta_z2 = np.arctan2(rotation_matrix[2, 1], -rotation_matrix[2, 0])
    array = np.array([theta_z1, theta_y, theta_z2])
    return array

def zyz_fixed_angles_to_rotation_matrix(angles):
    theta_z1, theta_y, theta_z2 = angles
    
    # Compute rotation matrices for each axis
    Rz1 = np.array([[np.cos(theta_z1), -np.sin(theta_z1), 0],
                    [np.sin(theta_z1), np.cos(theta_z1), 0],
                    [0, 0, 1]])
    
    Ry = np.array([[np.cos(theta_y), 0, np.sin(theta_y)],
                   [0, 1, 0],
                   [-np.sin(theta_y), 0, np.cos(theta_y)]])
    
    Rz2 = np.array([[np.cos(theta_z2), -np.sin(theta_z2), 0],
                    [np.sin(theta_z2), np.cos(theta_z2), 0],
                    [0, 0, 1]])
    
    # Combine rotation matrices
    rotation_matrix = Rz2 @ Ry @ Rz1
    
    return np.round(rotation_matrix, decimals=3)

In [ ]:
def test_rotation_to_zyz_fixed_angles():
    rotation_matrix = np.array([[0.707, -0.707, 0],
                                [0.707, 0.707, 0],
                                [0, 0, 1]])

    print("Rotation Matrix:")
    print(rotation_matrix)
    print("")

    # Convert rotation matrix to ZYZ fixed angles
    zyz_angles = rotation_matrix_to_zyz_fixed_angles(rotation_matrix)
    print("ZYZ Fixed Angles:")
    print(zyz_angles)
    print("")

    # Convert ZYZ fixed angles back to rotation matrix
    reversed_rotation_matrix = zyz_fixed_angles_to_rotation_matrix(zyz_angles)
    print("Reversed Rotation Matrix (ZYZ Fixed Angles):")
    print(reversed_rotation_matrix)
    print("")

test_rotation_to_zyz_fixed_angles()